config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :accounts, only: [:create]
  resources :cards, except: [:index, :new]
  resources :characters, only: [:index]
  resources :sessions, only: [:create]
  resources :topics, only: [:index]

  post "/idea_boards/:idea_board_id/cards/:card_id" => "idea_cards#create", as: :add_idea_card
  delete "/idea_boards/:idea_board_id/cards/:card_id" => "idea_cards#destroy", as: :remove_idea_card

  get "/cards/new/:type" => "cards#new", as: :new_card
  get "/cards/:card_id/tags/:type" => "card_tags#index", as: :list_card_tags
  post "/cards/:card_id/tags/:type" => "card_tags#create", as: :add_card_tag
  delete "/cards/:card_id/tags/:type" => "card_tags#destroy", as: :remove_card_tag

  get "/sign-up" => "accounts#new", as: :sign_up
  get "/me" => "accounts#profile", as: :profile
  get "/me/delete" => "accounts#confirm_destroy", as: :please_delete_me
  post "/me/delete" => "accounts#destroy", as: :delete_me_now

  get "/sign-in" => "sessions#new", as: :sign_in
  get "/sign-out" => "sessions#destroy", as: :sign_out

  get "/pages/:page" => "pages#show"

  get "/search" => "search#index", as: :search

  constraints format: /\.html/ do
    get "*not_found.:format" => "pages#not_found"
  end
end

app/models/card_tag.rb
class CardTag < ApplicationRecord
  belongs_to :card
  belongs_to :tag
end

app/controllers/card_tags_controller.rb
class CardTagsController < ApplicationController
  helper_method :card

  def index
    @tags = card.tags.of_type(params[:type])
  end

  def create
    card.add_tag(canonical_tag)
    redirect_to list_card_tags_path
  end

  def destroy
    card.remove_tag(canonical_tag)
    redirect_to list_card_tags_path
  end

protected

  def canonical_tag
    Tag.of_type(tag_params[:type]).with_canonical_name(tag_params[:canonical_name]).first
  end

  def tag_params
    params.require(:tag).permit(:canonical_name, :type, :variant)
  end

  def card
    @card ||= Card.find_by_id(params[:card_id])
  end
end

app/views/card_tags/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-sm-8">
      <%= render partial: "cards/abstract", locals: { card: card } %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <%= form_for(Topic.new, as: :tag, url: add_card_tag_path) do |form| %>
        <%= form.hidden_field(:type) %>
        <%= form.select(:canonical_name, Topic.select_options(Topic.canonical.where.not(id: card.tags))) %>
        <%= form.submit("Add Topic") %>
      <% end %>
    </div>
    <div class="col-sm">
      <%= form_for(Character.new, as: :tag, url: add_card_tag_path) do |form| %>
        <%= form.hidden_field(:type) %>
        <%= form.select(:canonical_name, Character.select_options(Character.canonical.where.not(id: card.tags))) %>
        <%= form.submit("Add Character") %>
      <% end %>
    </div>
  </div>
  <% card.tags.each do |tag| %>
    <div class="row">
      <div class="col-sm">
        <div class="alert alert-secondary">
          <%= tag.canonical_name %>
          <%= form_for(tag, as: :tag, url: remove_card_tag_path(type: tag.type, card_id: card.id), method: :delete, class: "close") do |form| %>
            <%= form.hidden_field(:type) %>
            <%= form.hidden_field(:canonical_name) %>
            <%= form.submit "&times;".html_safe %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>