config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :accounts, only: [:create]
  resources :cards, except: [:index, :new]
  resources :characters, only: [:index]
  resources :sessions, only: [:create]
  resources :topics, only: [:index]

  post "/idea_boards/:idea_board_id/cards/:card_id" => "idea_cards#create", as: :add_idea_card
  delete "/idea_boards/:idea_board_id/cards/:card_id" => "idea_cards#destroy", as: :remove_idea_card

  get "/cards/new/:type" => "cards#new", as: :new_card
  get "/cards/:card_id/tags/:type" => "card_tags#index", as: :list_card_tags
  post "/cards/:card_id/tags/:type" => "card_tags#create", as: :add_card_tag
  delete "/cards/:card_id/tags/:type" => "card_tags#destroy", as: :remove_card_tag

  get "/sign-up" => "accounts#new", as: :sign_up
  get "/me" => "accounts#profile", as: :profile
  get "/me/delete" => "accounts#confirm_destroy", as: :please_delete_me
  post "/me/delete" => "accounts#destroy", as: :delete_me_now

  get "/sign-in" => "sessions#new", as: :sign_in
  get "/sign-out" => "sessions#destroy", as: :sign_out

  get "/pages/:page" => "pages#show"

  get "/search" => "search#index", as: :search

  constraints format: /\.html/ do
    get "*not_found.:format" => "pages#not_found"
  end
end

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footerinfo">
    <div class="footerleft">
      <h5>Resources</h5>
        <%= external_link_to "C4tK Homepage", "http://www.codeforthekingdomnashville.org/" %>
        <%= external_link_to "Project Source Code", "https://github.com/mellowfish/c4tk-2018" %>
    </div>
    <div class="footerright">
      <h5>Contributors</h5>
      <div class="footerflex">
        <p>Alan Pramuk (Front End)</p>
        <%= external_link_to("https://github.com/alanpramuk9") { fa_icon("github") }%>
      </div>
      <div class="footerflex">
        <p>Christopher Coleman (Back End)</p>
        <%= external_link_to("https://twitter.com/mellowfish") { fa_icon("twitter") } %>
        <%= external_link_to("https://github.com/mellowfish") { fa_icon("github") } %>
      </div>
      <div class="footerflex">
        <p>Kevin Adelsberger (UX)</p>
        <%= external_link_to("https://twitter.com/k_adelsberger") { fa_icon("twitter") } %>
      </div>
      <div class="footerflex">
        <p>Santhosh Dasari (Idea Guy, original pitch)</p>
        <%= external_link_to("mailto:santhosh.dasari@gmail.com") { fa_icon("envelope") } %>

      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-md <%= current_page?(root_path) ? "navbar-trans" : "bg-light navbar-light" %>">
  <%= link_to(root_path, class: "navbar-brand") do %>
    <%= image_tag("icons/logo.svg", class: "logo") %>
  <% end %>
  <button class="navbar-toggler square custom-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <% unless current_user.guest? %>
        <li class="nav-item dropdown">
          <a class="nav-link top dropdown-toggle" style="min-width:200px;" href="#" id="navbardrop" data-toggle="dropdown">
            Add Idea Card
          </a>
          <div class="dropdown-menu">
            <% Card::TYPES.each do |card_type| %>
              <%= link_to card_type, new_card_path(type: card_type), class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      <% end %>
      <% if current_user.guest? %>
        <li class="nav-item">
          <%= link_to "Sign In", sign_in_path, class: "nav-link top" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link top" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "My Profile", profile_path, class: "nav-link top" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", sign_out_path, class: "nav-link top" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>