config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :accounts, only: [:create]
  resources :cards, except: [:index, :new]
  resources :characters, only: [:index]
  resources :sessions, only: [:create]
  resources :topics, only: [:index]

  post "/idea_boards/:idea_board_id/cards/:card_id" => "idea_cards#create", as: :add_idea_card
  delete "/idea_boards/:idea_board_id/cards/:card_id" => "idea_cards#destroy", as: :remove_idea_card

  get "/cards/new/:type" => "cards#new", as: :new_card
  get "/cards/:card_id/tags/:type" => "card_tags#index", as: :list_card_tags
  post "/cards/:card_id/tags/:type" => "card_tags#create", as: :add_card_tag
  delete "/cards/:card_id/tags/:type" => "card_tags#destroy", as: :remove_card_tag

  get "/sign-up" => "accounts#new", as: :sign_up
  get "/me" => "accounts#profile", as: :profile
  get "/me/delete" => "accounts#confirm_destroy", as: :please_delete_me
  post "/me/delete" => "accounts#destroy", as: :delete_me_now

  get "/sign-in" => "sessions#new", as: :sign_in
  get "/sign-out" => "sessions#destroy", as: :sign_out

  get "/pages/:page" => "pages#show"

  get "/search" => "search#index", as: :search

  constraints format: /\.html/ do
    get "*not_found.:format" => "pages#not_found"
  end
end

app/models/card.rb
class Card < ApplicationRecord
  TYPES = %w(Song Audio Video Picture Quote Passage Joke Story).sort

  belongs_to :user
  has_many :card_tags
  has_many :tags, through: :card_tags

  scope :of_type, ->(type) { where(type: type) }

  validates :user, presence: true

  def self.as_type(type)
    type ||= "Quote"
    type = type.camelize
    type = "Quote" unless Kernel.const_defined?(type)
    klass = Kernel.const_get(type)
    klass = Quote if klass.is_a?(Card)
    klass.new
  end

  def add_tag(tag)
    card_tags.find_or_create_by(tag: tag)
  end

  def remove_tag(tag)
    card_tags.where(tag: tag).delete_all
  end

  def type_identifier
    type.downcase
  end

  def display_title
    title || default_display_title
  end

  def default_display_title
    "A #{type}" if persisted?
  end
end

class Audio < Card
  validates :url, presence: true

  def default_display_title
    "An Audio File" if persisted?
  end
end

class Song < Card
  validates :url, presence: true
end

class Video < Card
  validates :url, presence: true
end

class Picture < Card
  validates :url, presence: true
end

class Quote < Card
  validates :author, presence: true
  validates :quote, presence: true
end

class Passage < Card
  validates :author, presence: true
  validates :source, presence: true
  validates :quote, presence: true
end

class Joke < Card
  validates :quote, presence: true
end

class Story < Card
  validates :quote, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :ensure_logged_in
  before_action :ensure_valid_card_type

  helper_method :card, :card_type

  def new; end

  def create
    card.assign_attributes(card_params)
    if card.save
      redirect_to card_path(card)
    else
      render :new
    end
  end

  def show; end

  def edit
    render :new
  end

  def update
    card.assign_attributes(card_params)
    if card.save
      redirect_to card_path(card)
    else
      render :new
    end
  end

  def destroy
    card.destroy if card.user == current_user
    redirect_to profile_path
  end

private

  def card_params
    params
      .require(:card)
      .permit(
        :id, :type, :user_id, :title, :description,
        :quote, :url, :source, :author, :location,
        :private, :review_status, :censored
      )
  end

  def ensure_valid_card_type
    if params[:type].present? && params[:type] != card.type
      redirect_to new_card_path(card.type)
    end
  end

  def card
    @card ||= Card.find_by_id(params[:id])
    @card ||= current_user.build_card_of_type(card_type)
  end

  def card_type
    params[:type] || params[:card][:type]
  end
end

app/views/cards/_abstract.html.erb
<div class="result">
  <div class="flexible">
    <%= image_tag("icons/#{card.type_identifier}.svg", class: "filetype")%>
    <%= render partial: "cards/abstract_content" %>
    <div class="rightcontent">
      <div></div>
      <div class="modal-toggle" data-toggle="modal" data-target="#cardModal<%= card.id %>">
        <%= image_tag("icons/more_info.svg")%>
      </div>
    </div>
  </div>
</div>
<%= render partial: "cards/modal", locals: { card: card } %>

app/views/cards/_abstract_content.html.erb
<div class="content">
  <p><%= card.title %></p>
  <% case card %>
  <% when Song, Video %>
    <%= external_link_to card.url %>
  <% when Picture %>
    <%= image_tag card.url, class: "img-thumbnail", style: "max-width: 200px; max-height: 100px" %>
  <% when Audio %>
    <% if card.source.present? %>
      <%= card.source %>
    <% else %>
      <%= external_link_to card.url %>
    <% end %>
  <% else %>
    <%= truncate(card.quote, length: 150) %>
  <% end %>
</div>

app/views/cards/_modal.html.erb
<div class="modal fade" id="cardModal<%= card.id %>" tabindex="-1">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header mh">
        <div class="modalflex">
          <h3 class="modal-title"><%= card.title %></h3>
          <p class="date">Added <%= card.created_at.to_formatted_s(:standard) %></p>
        </div>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="modal-body mb">
        <% case card %>
        <% when Song, Video %>
          <% if youtube_url?(card.url) %>
            <%= card_youtube_iframe(card) %>
          <% else %>
            <%= external_link_to card.url %>
          <% end %>
        <% when Picture %>
          <%= image_tag card.url, class: "img-thumbnail", style: "max-width: 600px; max-height: 300px" %>
        <% when Audio %>
          <audio controls>
            <source src="<%= card.url %>" type="audio/mpeg">
            Your browser does not support the audio element.
          </audio>
          <p><%= card.source %></p>
        <% else %>
          <p style="font-size:1.2em"><%= card.quote %></p>
          <p style="float:right; opacity:.8;">
            <% if card.source.present? %>
              <% if card.url.present? %>
                <%= external_link_to card.source, card.url %>
              <% else %>
                <%= card.source %>
              <% end %>
            <% else %>
              <%= external_link_to card.url %>
            <% end %>
          </p>
        <% end %>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btnmodal" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<% title "Add a Card" %>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-8 wrapper">
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <h3 id="addcard">Add a <%= card_type %> Card</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            <%= form_for(card, as: :card, url: card.persisted? ? card_path(card) : cards_path) do |form| %>
              <%= form.hidden_field(:type) %>
              <%= form.hidden_field(:user_id) %>
              <%= render partial: "shared/form/text_field", locals: {form: form, attribute: :title} %>
              <%= render partial: "shared/form/text_area", locals: {form: form, attribute: :description} %>
              <%= render partial: "shared/form/checkbox", locals: {form: form, attribute: :private} %>
              <%= render partial: "shared/form/text_field", locals: {form: form, attribute: :url} %>
              <%= render partial: "shared/form/text_area", locals: {form: form, attribute: :quote} %>
              <%= render partial: "shared/form/text_field", locals: {form: form, attribute: :source} %>
              <%= render partial: "shared/form/text_field", locals: {form: form, attribute: :author} %>
              <%= render partial: "shared/form/text_field", locals: {form: form, attribute: :location} %>
              <div class="form-group row">
                <div class="col-sm-2">
                  <%= link_to("Cancel", root_path, class: "btn btn-secondary") %>
                </div>
                <div class="col-sm-8"></div>
                <div class="col-sm-2 text-right">
                  <%= form.submit(card.persisted? ? "Update" : "Add", class: "btn btn-primary") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cards/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h3><%= card.title %></h3>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-sm">
      <p class="mb-0"><%= card.description %></p>
      <cite>Added <%= card.created_at.to_formatted_s(:standard) %></cite>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <% if card.private? %>
        <span class="badge badge-secondary">Private</span>
      <% else %>
        <span class="badge badge-success">Public</span>
      <% end %>
    </div>
    <div class="col-sm text-right">
      <%= link_to("Edit Topics", list_card_tags_path(card_id: card.id, type: :topic), class: "btn btn-primary") %>
      <%= link_to("Edit Details", edit_card_path(card), class: "btn btn-secondary") %>
    </div>
  </div>
  <hr>
  <div class="container">
    <div class="row">
      <div class="col-sm-2 text-right">
        <%= image_tag("icons/#{card.type_identifier}.svg", class: "card-icon") %>
      </div>
      <div class="col-sm-10">
        <% case card %>
        <% when Video, Song %>
          <% if youtube_url?(card.url) %>
            <%= card_youtube_iframe(card) %>
            <dl>
              <% if card.author.present? %>
                <dt>Author</dt>
                <dd><%= card.author %></dd>
              <% end %>
              <dt>Source</dt>
              <dd><%= card.source %></dd>
            </dl>
          <% else %>
            <dl>
              <dt>URL</dt>
              <dd><%= card.url %></dd>
              <% if card.author.present? %>
                <dt>Author</dt>
                <dd><%= card.author %></dd>
              <% end %>
              <dt>Source</dt>
              <dd><%= card.source %></dd>
            </dl>
          <% end %>
        <% when Audio %>
          <audio controls>
            <source src="<%= card.url %>" type="audio/mpeg">
            Your browser does not support the audio element.
          </audio>
          <dl>
            <% if card.author.present? %>
              <dt>Author</dt>
              <dd><%= card.author %></dd>
            <% end %>
            <dt>Source</dt>
            <dd><%= card.source %></dd>
          </dl>
        <% when Picture %>
          <%= image_tag card.url, class: "img-thumbnail", style: "max-width: 600px; max-height: 300px" %>
          <dl>
            <% if card.author.present? %>
              <dt>Author</dt>
              <dd><%= card.author %></dd>
            <% end %>
            <dt>Source</dt>
            <dd><%= card.source %></dd>
          </dl>
        <% else %>
          <blockquote class="blockquote">
            <p class="mb-0"><%= card.quote %></p>
            <footer class="blockquote-footer text-right">
              <% if card.author.present? %>
                From <%= card.author %> in
              <% end %>
              <cite title="Source">
                <% if card.url.present? %>
                  <%= external_link_to card.source, card.url %>
                <% else %>
                  <%= card.source %>
                <% end %>
              </cite>
            </footer>
          </blockquote>
        <% end %>
      </div>
    </div>
  </div>
</div>