config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :accounts, only: [:create]
  resources :cards, except: [:index, :new]
  resources :characters, only: [:index]
  resources :sessions, only: [:create]
  resources :topics, only: [:index]

  post "/idea_boards/:idea_board_id/cards/:card_id" => "idea_cards#create", as: :add_idea_card
  delete "/idea_boards/:idea_board_id/cards/:card_id" => "idea_cards#destroy", as: :remove_idea_card

  get "/cards/new/:type" => "cards#new", as: :new_card
  get "/cards/:card_id/tags/:type" => "card_tags#index", as: :list_card_tags
  post "/cards/:card_id/tags/:type" => "card_tags#create", as: :add_card_tag
  delete "/cards/:card_id/tags/:type" => "card_tags#destroy", as: :remove_card_tag

  get "/sign-up" => "accounts#new", as: :sign_up
  get "/me" => "accounts#profile", as: :profile
  get "/me/delete" => "accounts#confirm_destroy", as: :please_delete_me
  post "/me/delete" => "accounts#destroy", as: :delete_me_now

  get "/sign-in" => "sessions#new", as: :sign_in
  get "/sign-out" => "sessions#destroy", as: :sign_out

  get "/pages/:page" => "pages#show"

  get "/search" => "search#index", as: :search

  constraints format: /\.html/ do
    get "*not_found.:format" => "pages#not_found"
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  helper_method :user

  def new
    redirect_to(profile_path) unless user.guest?
  end

  def create
    @user = Users.create(**user_params)
    if user.guest?
      render :new
    else
      Users.store_user_in_session(session: session, user: user)
      redirect_to profile_path
    end
  end

  def profile; end

private

  def user
    @user ||= current_user
  end

  def user_params
    params_as_hash(params.require(:account).permit(:email, :id, :password, :password_confirmation, :name))
  end

  def session_params
    params_as_hash(params.require(:account).permit(:email, :password))
  end
end

app/views/accounts/new.html.erb
<% title "Sign Up" %>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md 8">
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <h3>Create an Account</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            <%= form_for(user, as: :account, url: accounts_path) do |form| %>
              <%= render partial: "shared/form/text_field", locals: {form: form, attribute: :name} %>
              <%= render partial: "shared/form/text_field", locals: {form: form, attribute: :email} %>
              <%= render partial: "shared/form/password_field", locals: {form: form, attribute: :password} %>
              <div class="form-group row">
                <div class="col-sm-2">
                  <%= link_to("Cancel", root_path, class: "btn btn-secondary") %>
                </div>
                <div class="col-sm-8"></div>
                <div class="col-sm-2 text-right">
                  <%= form.submit("Sign Up", class: "btn btn-primary") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<% title "My Profile" %>
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h3>My Profile</h3>
      <p>So Exciting!</p>
    </div>
  </div>
</div>